App/admin/routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for, make_response, send_file, jsonify, current_app, send_from_directory, abort
from flask_login import login_required, current_user
from sqlalchemy import asc
from sqlalchemy.orm import make_transient
# from flask_jwt_extended.tokens import _encode_jwt, _decode_jwt
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from datetime import datetime
from collections import defaultdict
from bs4 import BeautifulSoup
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, PageBreak, Paragraph, Image, Spacer, Flowable, KeepTogether
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from reportlab.lib.styles import ParagraphStyle, TA_LEFT, TA_RIGHT, TA_CENTER
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import io, os, locale, json, tempfile, random, string

from App.models import User, DataPangan, Kebun, db, Forum, Artikel
# from App import admin, login_manager, socketio

admin_page = Blueprint('admin_page', __name__)

# locale.setlocale(locale.LC_ALL, 'id_ID.UTF-8')

def petani_unique_id(prefix="PR_", string_length=2, number_length=4):
    """
    Generates a unique ID in the format PR_AB1234.

    Args:
        prefix: The static identifier prefix (default: "KR_").
        string_length: The length of the random string part (default: 2).
        number_length: The length of the random number part (default: 4).

    Returns:
        A unique ID string.
    """
    random_string = ''.join(random.choices(string.ascii_uppercase, k=string_length))
    random_number = ''.join(random.choices(string.digits, k=number_length))
    unique_id = f"{prefix}{random_string}{random_number}"
    return unique_id

def ahli_unique_id(prefix="EXP_", string_length=2, number_length=4):
    """
    Generates a unique ID in the format EXP_AB1234.

    Args:
        prefix: The static identifier prefix (default: "KR_").
        string_length: The length of the random string part (default: 2).
        number_length: The length of the random number part (default: 4).

    Returns:
        A unique ID string.
    """
    random_string = ''.join(random.choices(string.ascii_uppercase, k=string_length))
    random_number = ''.join(random.choices(string.digits, k=number_length))
    unique_id = f"{prefix}{random_string}{random_number}"
    return unique_id

def save_verification_document(user, document):
    filename = secure_filename(document.filename)
    relative_path = f'verification_docs/{user.id}/{filename}'
    full_path = os.path.join(current_app.config['UPLOAD_FOLDER'], relative_path)
    
    # Buat direktori jika belum ada
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    
    document.save(full_path)
    user.verification_document = relative_path
    db.session.commit()

@admin_page.route("/admin-dashboard", methods=['POST', 'GET'])
@login_required
def index():
    if current_user.role == 'user':
        return redirect(url_for('views.dashboard'))

    user = User.query.all()
    kelurahan = Kebun.query.all()
    produksi = DataPangan.query.all()

    # Mengakumulasi total panen berdasarkan kelurahan_id
    total_panen_per_kelurahan = defaultdict(int)
    for data in produksi:
        try:
            total_panen_per_kelurahan[data.kelurahan_id] += data.jml_panen
        except Exception as e:
            # Menangani error jika terjadi saat menambahkan data ke total_panen_per_kelurahan
            print(f"Error saat menambahkan data panen ke total_panen_per_kelurahan: {e}")

    try:
        total_kebun = sum(kel.kebun for kel in kelurahan)
    except Exception as e:
        # Menangani error jika terjadi saat menghitung total_kebun
        print(f"Error saat menghitung total kebun: {e}")
        total_kebun = 0

    try:
        total_panen = sum(prod.jml_panen for prod in produksi)
    except Exception as e:
        # Menangani error jika terjadi saat menghitung total_panen
        print(f"Error saat menghitung total panen: {e}")
        total_panen = 0

    stat_cabai = []
    stat_tomat = []
    for panenCabai in DataPangan.query.filter_by(komoditas='Cabai').all():
        totalCabai = panenCabai.jml_panen
        stat_cabai.append(totalCabai)
    for panenTomat in DataPangan.query.filter_by(komoditas='Tomat').all():
        totalTomat = panenTomat.jml_panen
        stat_tomat.append(totalTomat)

    totalPanenCabai = sum(stat_cabai)
    totalPanenTomat = sum(stat_tomat)

    if not current_user.is_authenticated:
        redirect(url_for('views.adminLogin'))
    return render_template('admin-dashboard/index.html', user=user, kelurahan=kelurahan, produksi=produksi, total_panen_per_kelurahan=total_panen_per_kelurahan, total_kebun=total_kebun, total_panen=total_panen, round_num=round, genhash=generate_password_hash, checkhash=check_password_hash, totalPanenCabai=totalPanenCabai, totalPanenTomat=totalPanenTomat)

@admin_page.route('/admin-dashboard/<string:username>/profil', methods=['POST', 'GET'])
@login_required
def profile(username):
    print(current_user.role)
    user = User.query.filter_by(username=username).first()
    return render_template('admin-dashboard/profile.html', user=user)

@admin_page.route('/admin-dashboard/<int:id>/profil/update-username', methods=['GET', 'POST'])
@login_required
def updateusername(id):
    user = User.query.get_or_404(id)
    password = request.form['userPass']

    if request.method == 'POST':
        if check_password_hash(current_user.password, password):
            user.username = request.form['username']
            db.session.commit()
            flash('Username berhasil diubah!', category='success')  # Assuming you have a flash message system
            return redirect((request.referrer))  # For successful update
        else:
            # Handle incorrect password scenario (e.g., flash a message or redirect)
            flash('Kata sandi salah, silakan coba lagi!', category='error')  # Assuming you have a flash message system
            return redirect(url_for('admin_page.profile', username=user.username))  # Redirect back to the form
        
@admin_page.route('/admin-dashboard/<int:id>/profil/update-password', methods=['GET', 'POST'])
@login_required
def updatepassword(id):
    user = User.query.get_or_404(id)
    oldpass = request.form['old-pass']
    newpass = request.form['new-pass']
    confnewpass = request.form['new-pass-conf']

    if request.method == 'POST':
        if check_password_hash(current_user.password, oldpass):
            if confnewpass != newpass:
                flash('Konfirmasi kata sandi tidak cocok!', 'error')
            else:
                user.password = generate_password_hash(newpass, method='pbkdf2')
                db.session.commit()
                flash('Kata sandi berhasil diperbarui!', category='success')  # Assuming you have a flash message system
                return redirect((request.referrer))  # For successful update
        else:
            # Handle incorrect password scenario (e.g., flash a message or redirect)
            flash('Kata sandi salah, silakan coba lagi!', category='error')  # Assuming you have a flash message system
            return redirect(url_for('admin_page.profile', username=user.username))  # Redirect back to the form

@admin_page.route('/admin-dashboard/user-management')
@login_required
def user_mgn():
    users = User.query.filter(User.role != 'admin').all()
    users_data = [
    {
        'id': user.id,
        'username': user.username,
        'email': user.email,
        'nama_lengkap': getattr(user, 'nama_lengkap', None),
        'role': user.role,
        'is_confirmed': user.is_confirmed,
        'petani_request': user.petani_request,
        'ahli_request': user.ahli_request,
        'verification_document': user.verification_document if hasattr(user, 'verification_document') else None
    }
        for user in users
    ]
    return render_template('admin-dashboard/user-management.html', users_data=users_data)

@admin_page.route('/verify_upgrades')
@login_required
def verify_upgrades():
    petani_requests = User.query.filter_by(petani_request=True, is_verified=False).all()
    ahli_requests = User.query.filter_by(ahli_request=True, is_verified=False).all()
    return render_template('admin/verify_upgrades.html', petani_requests=petani_requests, ahli_requests=ahli_requests)

@admin_page.route('/verification_docs/<path:filename>')
@login_required
def view_document(filename):
    # Pastikan hanya admin yang bisa mengakses
    if current_user.role != 'admin':
        abort(403)
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], filename)

@admin_page.route('/admin-dashboard/approve-upgrade/<int:user_id>', methods=['POST'])
@login_required
def approve_upgrade(user_id):
    user = User.query.get_or_404(user_id)
    additional_info = getattr(user, 'additional_info', {}) or {}

    try:
        if user.ahli_request:
            # Update user yang ada menjadi Ahli
            user.role = 'ahli'
            user.is_verified = True
            user.unique_id = ahli_unique_id()
            user.bidang_keahlian = additional_info.get('bidang_keahlian')
            user.gelar = additional_info.get('gelar')
            user.ahli_request = False
        elif user.petani_request:
            # Update user yang ada menjadi Petani
            user.role = 'petani'
            user.is_verified = True
            user.unique_id = petani_unique_id()
            user.luas_lahan = additional_info.get('luas_lahan')
            user.petani_request = False

        db.session.commit()
        return jsonify({'success': True, 'message': 'User upgrade approved'})
    except Exception as e:
        db.session.rollback()
        print(f"Error during upgrade: {str(e)}")

App/templates/admin-dashboard/articles-management.html
{% extends 'admin-dashboard/layout.html' %} {% block title %} Dashboard - User Management {% endblock %} {% block container %}
<div class="container-fluid">
    <h2 class="fw-bolder">Articles Management</h2>
    <p class="text-muted mb-4">Manage articles here</p>
    <div class="row mb-3">
        <div class="col-md-6 col-sm-12 mb-lg-0 mb-sm-3">
            <input type="text" id="searchInput" class="form-control bg-light" placeholder="Search users..." />
        </div>
        <div class="col-md-6 col-sm-12">
            <select id="roleFilter" class="form-select bg-light">
                <option value="">All Roles</option>
                <option value="personal">Personal</option>
                <option value="petani">Petani</option>
                <option value="ahli">Ahli</option>
            </select>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-light table-hover">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Judul</th>
                    <th scope="col">Created At</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for article in all_data %}
                <tr class="align-middle">
                    <td>{{ loop.index }}</td>
                    <td class="text-truncate" style="max-width: 132px">{{ article.judul or 'N/A' }}</td>
                    <td>{{ article.created_at }}</td>
                    <td>{{ article.created_by }}</td>
                    <!-- Nama lengkap user yang dibuat -->
                    <td>
                        <div class="d-flex gap-2">
                            <span class="badge {% if article.is_drafted %} bg-secondary {% else %} bg-success {% endif %}"> {% if article.is_drafted %} Drafted {% else %} Posted {% endif %} </span>
                            <span class="badge {% if article.is_approved %} bg-success {% else %} bg-warning {% endif %}"> {% if article.is_approved %} Approved {% else %} Disapproved {% endif %} </span>
                        </div>
                    </td>
                    <td>
                        <button class="btn btn-sm btn-info" data-bs-toggle="modal" data-bs-target="#articlesDetailModal{{article.id}}">Details</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center" id="pagination">
            <!-- Pagination will be populated here -->
        </ul>
    </nav>
</div>

<!-- Modal for user details -->
{% for item in all_data %}
<div class="modal fade" id="articlesDetailModal{{ item.id }}" tabindex="-1" aria-labelledby="articlesDetailModal{{ item.id }}Label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="articlesDetailModal{{ item.id }}Label">Article Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="userDetailsBody">
                <p><strong>Judul:</strong> {{item.judul}}</p>
                <p><strong>Oleh:</strong> {{item.created_by}}</p>
                <p><strong>Dibuat pada:</strong> {{item.created_at}}</p>
                <p><strong>Konten:</strong> {{item.content | safe}}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                <a href="{{ url_for('admin_page.approve_article', id=item.id ) }}" role="button" class="btn btn-primary {% if item.is_drafted or item.is_approved %} disabled {% endif %}" {% if item.is_drafted %} disabled {% endif %}
                    >Setujui Artikel</a
                >
            </div>
        </div>
    </div>
</div>
{% endfor %}

<!-- Modal for user verification -->
<div class="modal fade" id="userVerificationModal" tabindex="-1" aria-labelledby="userVerificationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="userVerificationModalLabel">Verify User Upgrade Request</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="userVerificationBody">...</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success" id="approveUpgradeBtn">Approve</button>
                <button type="button" class="btn btn-danger" id="rejectUpgradeBtn">Reject</button>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block scripts %} {% endblock %}

App/templates/admin-dashboard/layout.html
<!DOCTYPE html>
<html lang="en" class="min-vh-100 h-100">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %} {% endblock %}</title>

        <meta name="keywords" content="rindang sistem informasi pangan kota ternate kebutuhan cabai barito rica tanam petani" />
        <meta name="description" content="Rindang: Platform pangan online untuk Kota Ternate. Pangan murah, berkualitas, dan pemberdayaan petani." />
        <meta property="og:title" content="RINDANG - Rica Tanam Dalam Kampung" />
        <meta property="og:description" content="Sistem Informasi kebutuhan pangan dan informasi pangan Kota Ternate" />
        <meta property="og:image" content="https://i.ibb.co.com/8dynFyq/Rindang-OG-Thumbnail.jpg" />
        <meta property="og:url" content="https://rindang.net" />
        <meta property="og:type" content="website" />

        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicons/apple-touch-icon.png') }}" />
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicons/favicon-32x32.png') }}" />
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicons/favicon-16x16.png') }}" />
        <link rel="manifest" href="{{ url_for('static', filename='favicons/site.webmanifest') }}" />
        <link rel="mask-icon" href="{{ url_for('static', filename='favicons/safari-pinned-tab.svg') }}" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#ffc40d" />
        <meta name="theme-color" content="#ffffff" />

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xz/fonts@1/serve/plus-jakarta-display.min.css" />
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css' ) }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='admin/css/styles.min.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='admin/css/base-color.css') }}" />

        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
            integrity="sha512-Avb2QiuDEEvB4bZJYdft2mNjVShBftLdPG8FJ0V7irTLQ8Uo0qcPxh4Plq7G5tGm0rU+1SPhVotteLpBERwTkw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
        />

        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

        {% block head %} {% endblock %} {{ toastr.include_jquery() }} {{ toastr.include_toastr_css() }} {{ toastr.message() }}
    </head>

    <body class="h-100 bg-body-secondary">
        <div class="page-wrapper h-100" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar-position="fixed" data-header-position="fixed">
            <aside class="left-sidebar">
                <div>
                    <div class="brand-logo d-flex align-items-center justify-content-between">
                        <a href="{{ url_for('admin_page.index' ) }}" class="text-nowrap logo-img">
                            <img src="{{ url_for('static', filename='img/rindang-logo-red.svg') }}" width="180" alt="RINDANG Logo" />
                        </a>
                        <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                            <i class="ti ti-x fs-8"></i>
                        </div>
                    </div>

                    <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                        <ul id="sidebarnav">
                            <li class="nav-small-cap">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Home</span>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" href="{{ url_for('admin_page.index' ) }}" aria-expanded="false">
                                    <span>
                                        <i class="ti ti-grid-dots"></i>
                                    </span>
                                    <span class="hide-menu">Dashboard</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" href="{{ url_for('admin_page.user_mgn' ) }}" aria-expanded="false">
                                    <span>
                                        <i class="ti ti-users"></i>
                                    </span>
                                    <span class="hide-menu">User Management</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" href="{{ url_for('admin_page.articles_mgn' ) }}" aria-expanded="false">
                                    <span>
                                        <i class="ti ti-article"></i>
                                    </span>
                                    <span class="hide-menu">Articles Management</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" href="{{ url_for('views.mapbase' ) }}" target="_blank" aria-expanded="false">
                                    <span>
                                        <i class="ti ti-map"></i>
                                    </span>
                                    <span class="hide-menu">Peta Sebaran</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" href="{{ url_for('admin_page.dataproduksi' ) }}" aria-expanded="false">
                                    <span>
                                        <i class="ti ti-plant"></i>
                                    </span>
                                    <span class="hide-menu">Data Produksi</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </aside>

            <div class="body-wrapper h-100">
                <header class="app-header">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <ul class="navbar-nav">
                            <li class="nav-item d-block d-xl-none">
                                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                                    <i class="ti ti-menu-2"></i>
                                </a>
                            </li>
                        </ul>
                        <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                                <li class="nav-item">
                                    <div class="dropdown">
                                        <a class="nav-link gap-2" href="javascript:void(0)" id="drop2" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <img class="img-profile rounded-circle" src="{{ url_for('static', filename='admin/images/profile/user-1.jpg') }}" width="35" height="35" />
                                            <small class="mr-2 d-none d-lg-inline text-gray-600 small fw-bold" style="font-size: 11pt">{{ current_user.username }}</small>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                            <div class="message-body">
                                                <a href="{{ url_for('admin_page.profile', username=current_user.username) }}" class="d-flex align-items-center gap-2 dropdown-item">
                                                    <i class="ti ti-user fs-6"></i>
                                                    <p class="mb-0 fs-3">Profil</p>
                                                </a>
                                                <a href="{{ url_for('auth.logout') }}" class="btn btn-outline-green mx-3 mt-2 d-block">Keluar</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </header>
                {% block container %} {% endblock %}
            </div>
        </div>

        {{ toastr.include_toastr_js() }}

        <script src="{{ url_for('static', filename='admin/libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/sidebarmenu.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/app.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/libs/simplebar/dist/simplebar.js') }}"></script>

        {% block scripts %} {% endblock %}

        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
        ></script>
        <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.min.js"></script>
        <script src="https://unpkg.com/tippy.js@6/dist/tippy-bundle.umd.js"></script>

        <script>
            document.querySelectorAll('.dwldBtn').forEach((button) => {
                tippy(button, {
                    content: 'Export Laporan',
                });
            });

            document.querySelectorAll('.statBtn').forEach((button) => {
                tippy(button, {
                    content: 'Lihat Statistik',
                });
            });
        </script>
    </body>
</html>

App/templates/admin-dashboard/profile.html
{% extends 'admin-dashboard/layout.html' %} {% block page_title %} Dashboard - Pengaturan {% endblock %} {% block container %}

<div class="container-fluid">
    <!--  Row 1 -->
    <div class="row">
        <div class="col-lg-12 col-12 d-flex flex-column">
            <h3 class=""><strong>Akun Saya</strong></h3>
            <p class="mb-4">Anda dapat mengubah alamat E-Mail dan Kata Sandi disini</p>
            <div class="card">
                <div class="card-body text-lg-start d-flex flex-column gap-3 text-center">
                    <div class="text-lg-start text-center d-flex justify-content-between">
                        <div class="d-flex flex-wrap flex-column text-start my-auto">
                            <h4><strong class="text-muted">Username</strong></h4>
                            <p class="mb-0">{{ user.username }}</p>
                        </div>
                        <button id="updateUsernameBtn" type="button" class="btn btn-outline-dark my-auto" data-bs-toggle="modal" data-bs-target="#updateUsername">Ubah Username</button>
                    </div>
                    <div class="text-lg-start text-center d-flex flex justify-content-between">
                        <div class="d-flex flex-wrap flex-column text-start my-auto">
                            <h4><strong class="text-muted">Kata Sandi</strong></h4>
                            <p class="mb-0">*********</p>
                        </div>
                        <button id="updatePassBtn" type="button" class="btn btn-outline-dark my-auto" data-bs-toggle="modal" data-bs-target="#updatePass">Ubah Kata Sandi</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="updateUsername" tabindex="-1" aria-labelledby="updateUsernameLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content p-3">
            <div class="modal-header">
                <h1 class="modal-title fs-5 fw-bold" id="updateUsernameLabel">Username</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('admin_page.updateusername', id=current_user.id ) }}" method="post">
                    <div class="mb-3">
                        <label for="username" class="form-label fw-bold fs-4">Username</label>
                        <input class="form-control" type="text" name="username" id="username" placeholder="contoh : admin" value="{{ user.username }}" />
                    </div>
                    <div class="mb-3">
                        <label for="userPass" class="form-label fw-bold fs-4">Kata Sandi</label>
                        <input class="form-control" type="password" name="userPass" id="userPass" placeholder="Masukkan Kata Sandi" />
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-green w-100">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="updatePass" tabindex="-1" aria-labelledby="updatePassLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content p-3">
            <div class="modal-header">
                <h1 class="modal-title fs-5 fw-bold" id="updatePassLabel">Email</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('admin_page.updatepassword', id=current_user.id ) }}" method="post">
                    <div class="mb-3">
                        <label for="old-pass" class="form-label fw-bold fs-4">Kata Sandi Lama</label>
                        <input class="form-control" name="old-pass" id="old-pass" type="password" placeholder="Masukkan kata sandi lama anda" />
                    </div>
                    <div class="mb-3">
                        <label for="new-pass" class="form-label fw-bold fs-4">Kata Sandi Baru</label>
                        <input class="form-control" type="password" name="new-pass" id="new-pass" placeholder="Masukkan kata sandi baru" />
                    </div>
                    <div class="mb-3">
                        <label for="new-pass-conf" class="form-label fw-bold fs-4">Konfirmasi Kata Sandi Baru</label>
                        <input class="form-control" type="password" name="new-pass-conf" id="new-pass-conf" placeholder="Konfirmasi kata sandi baru" />
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-green w-100">Update Kata Sandi</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}